accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('<int:user_id>/', views.detail, name='detail'),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('<int:movie_id>/review/', views.create_review, name='create_review'),
    path('<int:review_id>/delete_review/', views.delete_review, name='delete_review'),
    path('<int:movie_id>/like/', views.like, name="like"),

]

pjt10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# User 모델을 Customizing 한다.

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

    

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genre = models.ManyToManyField(Genre, related_name='movies')
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_movies')

class Review(models.Model):
    content = models.CharField(max_length=40)
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reviews')

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ['username']
    

movies/forms.py
from django import forms
from .models import Movie, Review, Genre

class CommentForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['content', 'score']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
User = get_user_model()
# Create your views here.

def index(request):
    users = User.objects.all()
    print(users)
    context = {'users': users}
    return render(request,'accounts/index.html', context)

def signup(request):
    # if request.user.is_authenticated:
    #     return redirect('accounts:index')
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            next_page = request.GET.get('index')
            return redirect(next_page or 'accounts:index')
    
    else:
        form = CustomUserCreationForm()
    
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

def detail(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    reviews = user.reviews.all()
    movies = user.liked_movies.all()
    
    context = {
        'user': user,
        'reviews': reviews,
        'movies': movies,
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_page = request.GET.get('next')
            return redirect(next_page or 'accounts:index')

    else:
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form' : form})

def logout(reqeust):
    auth_logout(reqeust)
    return redirect('accounts:index')

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Genre, Review
from .forms import CommentForm


# Create your views here.

def index(request):
    movies = Movie.objects.all()

    return render(request, 'movies/index.html', {'movies': movies})

def detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    comment_form = CommentForm()

    return render(request, 'movies/detail.html', {'movie': movie, 'comment_form': comment_form})


def create_review(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    form = CommentForm(request.POST)

    if form.is_valid():
        print('들어감')
        comment = form.save(commit=False)
        comment.movie_id = movie_id
        comment.user_id = request.user.id
        comment.save()
    
    return redirect('movies:detail', movie_id)

def delete_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    movie_id = review.movie.id
    review.delete()

    return redirect('movies:detail', movie_id)

def like(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    user = request.user

    if movie.liked_users.filter(pk=user.id).exists():
        user.liked_movies.remove(movie)
    
    else:
        user.liked_movies.add(movie)
    
    return redirect('movies:detail', movie.id)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block title %}
상세보기
{% endblock title %}

{% block body %}

{{user.username}}
<br>
상세보기
<hr>
{% for review in reviews %}

{{review.content}}
{% empty %}
없다
{% endfor %}
<hr>
좋아하는 영화들

{% for movie in movies %}
<br>
{{movie.title}}
{% empty %}
없다

{% endfor %}
<hr>
팔로워 : {{user.followers.all | length}}
팔로잉 : {{user.followings.all | length}}

{% endblock body %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}


{% block title %}
홈
{% endblock title %}

{% block body %}
{% for user in users %}

<a href={% url 'accounts:detail' user.id %}>{{user.username}}</a>
<br>

{% empty %}
없다
{% endfor %}

{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
로긴
{% endblock title %}

{% block body %}

<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">로그인</button>
</form>
{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
회원가입
{% endblock title %}

{% block body %}

<form method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit">제출</button>
</form>

{% endblock body %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
영화 상세보기
{% endblock title %}


{% block body %}

{{ movie.title }}{% if user.is_authenticated %}

<a href="{% url 'movies:like' movie.id %}">좋아요</a>

{% endif %}
<br>
{{ movie.audience }}
<br>
{{ movie.description }}
<br>
{{ movie.poster_url }}
<br>
<hr>
좋아하는 사람들
<br>  
{% for user in movie.liked_users.all %}

{{user.username}}
<br>


{% endfor %}
<hr>
댓글 작성
{% if user.is_authenticated %}
<form method = "POST" action="{% url 'movies:create_review' movie.id %}">
{% csrf_token %}
{{comment_form.as_p}}
<button type="submit">댓글 작성</button>
</form>
{% endif %}
<hr>
댓글들

<br>
{% for review in movie.reviews.all %}
{{review.content}}
{% if user.id == review.user.id %}
<a href="{% url 'movies:delete_review' review.id %}"><button>x</button></a>{% endif %}
<br>
{% endfor %}


{% endblock body %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block title %}
영화
{% endblock title %}

{% block body %}

{% for movie in movies %}

{{movie.title}}
<br>
<br>
{{movie.description}}
<hr>
<br>
{% endfor %}

{% endblock body %}

pjt10/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title> {% block title %}
  {% endblock title %} </title>
</head>
<body>
  <a href={% url 'accounts:index' %}>홈</a>
  <a href={% url 'movies:index' %}>영화 홈</a>
  {% if user.is_authenticated %}
  <a href={% url 'accounts:logout' %}>로그아웃</a>
  {% else %}
  <a href={% url 'accounts:login' %}>로그인</a>
  {% endif %}
  <hr>

  {% block body %}
  {% endblock body %}
</body>
</html>